spring:
    data:
        mongodb:
            port: 27017
            uri: mongodb://localhost:27017/springsecuritypractice
            host: localhost
            database: springsecuritypractice
            
